name: Trigger Dispatch
on:
  push:
  workflow_dispatch:
jobs:
  trigger-dispatch:
    uses: alexxss/satis-github/.github/workflows/on-dispatch.yml@main
    with:
      package_name: ${{ vars.PACKAGE_NAME }}
    
